import { AntlersNode } from '../../runtime/nodes/abstractNode';
import { IScopeVariable } from '../scope/types';

export function makeAssetVariables(symbol: AntlersNode): IScopeVariable[] {
    return [
        { name: 'id', dataType: 'string', sourceName: '*internal.asset', sourceField: null, introducedBy: symbol },
        { name: 'title', dataType: 'string', sourceName: '*internal.asset', sourceField: null, introducedBy: symbol },
        { name: 'path', dataType: 'string', sourceName: '*internal.asset', sourceField: null, introducedBy: symbol },
        { name: 'filename', dataType: 'string', sourceName: '*internal.asset', sourceField: null, introducedBy: symbol },
        { name: 'basename', dataType: 'string', sourceName: '*internal.asset', sourceField: null, introducedBy: symbol },
        { name: 'extension', dataType: 'string', sourceName: '*internal.asset', sourceField: null, introducedBy: symbol },
        { name: 'is_asset', dataType: 'boolean', sourceName: '*internal.asset', sourceField: null, introducedBy: symbol },
        { name: 'is_audio', dataType: 'boolean', sourceName: '*internal.asset', sourceField: null, introducedBy: symbol },
        { name: 'is_previewable', dataType: 'boolean', sourceName: '*internal.asset', sourceField: null, introducedBy: symbol },
        { name: 'is_image', dataType: 'boolean', sourceName: '*internal.asset', sourceField: null, introducedBy: symbol },
        { name: 'is_svg', dataType: 'boolean', sourceName: '*internal.asset', sourceField: null, introducedBy: symbol },
        { name: 'is_video', dataType: 'boolean', sourceName: '*internal.asset', sourceField: null, introducedBy: symbol },
        { name: 'edit_url', dataType: 'string', sourceName: '*internal.asset', sourceField: null, introducedBy: symbol },
        { name: 'url', dataType: 'string', sourceName: '*internal.asset', sourceField: null, introducedBy: symbol },
        { name: 'permalink', dataType: 'string', sourceName: '*internal.asset', sourceField: null, introducedBy: symbol },
        { name: 'size', dataType: 'string', sourceName: '*internal.asset', sourceField: null, introducedBy: symbol },
        { name: 'size_bytes', dataType: 'number', sourceName: '*internal.asset', sourceField: null, introducedBy: symbol },
        { name: 'size_gigabytes', dataType: 'number', sourceName: '*internal.asset', sourceField: null, introducedBy: symbol },
        { name: 'size_kilobytes', dataType: 'number', sourceName: '*internal.asset', sourceField: null, introducedBy: symbol },
        { name: 'size_megabytes', dataType: 'number', sourceName: '*internal.asset', sourceField: null, introducedBy: symbol },
        { name: 'size_b', dataType: 'number', sourceName: '*internal.asset', sourceField: null, introducedBy: symbol },
        { name: 'size_kb', dataType: 'number', sourceName: '*internal.asset', sourceField: null, introducedBy: symbol },
        { name: 'size_mb', dataType: 'number', sourceName: '*internal.asset', sourceField: null, introducedBy: symbol },
        { name: 'size_gb', dataType: 'number', sourceName: '*internal.asset', sourceField: null, introducedBy: symbol },
        { name: 'focus', dataType: 'string', sourceName: '*internal.asset', sourceField: null, introducedBy: symbol },
        { name: 'focus_css', dataType: 'string', sourceName: '*internal.asset', sourceField: null, introducedBy: symbol },
        { name: 'height', dataType: 'number', sourceName: '*internal.asset', sourceField: null, introducedBy: symbol },
        { name: 'width', dataType: 'number', sourceName: '*internal.asset', sourceField: null, introducedBy: symbol },
        { name: 'orientation', dataType: 'string', sourceName: '*internal.asset', sourceField: null, introducedBy: symbol },
        { name: 'ratio', dataType: 'number', sourceName: '*internal.asset', sourceField: null, introducedBy: symbol },
        { name: 'mime_type', dataType: 'string', sourceName: '*internal.asset', sourceField: null, introducedBy: symbol },
        { name: 'duration', dataType: 'number', sourceName: '*internal.asset', sourceField: null, introducedBy: symbol },
        { name: 'duration_seconds', dataType: 'number', sourceName: '*internal.asset', sourceField: null, introducedBy: symbol },
        { name: 'duration_sec', dataType: 'number', sourceName: '*internal.asset', sourceField: null, introducedBy: symbol },
        { name: 'playtime', dataType: 'string', sourceName: '*internal.asset', sourceField: null, introducedBy: symbol },
    ];
}